let sim={ids:[],i:0,ans:{},started:0};
function renderSimulados(){
 let p=document.getElementById('p-simulados');let last=S.sims.slice(-5).reverse();
 p.innerHTML=`<div class="card"><h1>Simulados</h1><p>Use 10 e 20 questões durante a retomada. Quando ganhar ritmo, avance para 40 e 80.</p><div class="row">${[10,20,40,80].map(n=>`<button class="btn ${n===80?'amber':'secondary'}" onclick="startSim(${n})">${n} questões</button>`).join('')}</div><div class="notice">Meta de treinamento para simulados completos: <b>50+ acertos</b>. A regra definitiva do 49º EOU deve ser conferida no edital de 22/01/2027.</div></div><div id="simbox"></div><div class="card" style="margin-top:16px"><h2>Histórico recente</h2>${last.length?last.map(x=>`<p><b>${x.ok}/${x.total}</b> — ${fmtDate(new Date(x.at))} — ${Math.round(x.ok*100/x.total)}%</p>`).join(''):'<p class="muted">Nenhum simulado concluído.</p>'}</div>`
}
function startSim(n){sim={ids:shuffle(QUESTIONS).slice(0,n).map(x=>x.id),i:0,ans:{},started:Date.now()};renderSimQ()}
function renderSimQ(){let box=document.getElementById('simbox');if(sim.i>=sim.ids.length){finishSim();return}let q=QUESTIONS.find(x=>x.id===sim.ids[sim.i]);box.innerHTML=`<div class="card" style="margin-top:16px"><div class="row" style="justify-content:space-between"><span class="pill">${q.disc}</span><span>${sim.i+1}/${sim.ids.length}</span></div><h2>${esc(q.q)}</h2>${q.opts.map((o,i)=>`<label class="option"><input style="width:auto" type="radio" name="simopt" value="${i}" ${sim.ans[q.id]===i?'checked':''}> <b>${"ABCD"[i]}.</b> ${esc(o)}</label>`).join('')}<div class="row"><button class="btn secondary" onclick="simPrev()" ${sim.i===0?'disabled':''}>Anterior</button><button class="btn" onclick="simNext()">${sim.i===sim.ids.length-1?'Finalizar':'Próxima'}</button></div></div>`}
function saveSimChoice(){let qid=sim.ids[sim.i],r=document.querySelector('input[name=simopt]:checked');if(r)sim.ans[qid]=+r.value}
function simNext(){saveSimChoice();sim.i++;renderSimQ()} function simPrev(){saveSimChoice();sim.i=Math.max(0,sim.i-1);renderSimQ()}
function finishSim(){let ok=0;sim.ids.forEach(id=>{let q=QUESTIONS.find(x=>x.id===id),choice=sim.ans[id];let good=choice===q.ans;if(good)ok++;S.answers.push({qid:id,disc:q.disc,topic:q.topic,ok:good,chosen:choice,at:Date.now(),mode:'sim'});if(!good){let e=S.errors.find(x=>x.qid===id&&!x.mastered);if(e)e.count++;else S.errors.push({qid:id,disc:q.disc,topic:q.topic,count:1,type:'erro em simulado',created:Date.now(),nextReview:Date.now()+86400000,stage:0,mastered:false})}});let rec={at:Date.now(),total:sim.ids.length,ok,minutes:Math.round((Date.now()-sim.started)/60000)};S.sims.push(rec);save();let zone=sim.ids.length===80?(ok>=50?'Margem de segurança':ok>=40?'Zona de aprovação pela referência histórica recente':'Abaixo da meta'):(ok/sim.ids.length>=.625?'Bom ritmo':'Precisa reforço');document.getElementById('simbox').innerHTML=`<div class="card" style="margin-top:16px"><h2>Resultado</h2><div class="bigdate">${ok}/${sim.ids.length}</div><p><b>${zone}</b></p><p>Os erros foram enviados ao caderno de revisão.</p><button class="btn" onclick="renderSimulados()">Novo simulado</button></div>`}
function renderTutor(){
 let p=document.getElementById('p-tutor');p.innerHTML=`<div class="grid2"><div class="card"><h1>Tutor OAB local</h1><p>Funciona sem API paga. Ele usa seu histórico para montar orientação e sessões. Para explicações jurídicas abertas, copie o contexto para o ChatGPT gratuito.</p><div class="chat" id="chat">${S.chat.map(m=>`<div class="bubble ${m.who}">${esc(m.text)}</div>`).join('')}</div><div class="row" style="margin-top:10px"><input id="chatin" placeholder="Ex.: Vamos estudar / Tenho 40 minutos / Como estou?"><button class="btn" onclick="chatSend()">Enviar</button></div></div><div class="card"><h2>Atalhos</h2><div class="row"><button class="btn secondary" onclick="chatPreset('Vamos estudar')">Vamos estudar</button><button class="btn secondary" onclick="chatPreset('Tenho 40 minutos')">Tenho 40 minutos</button><button class="btn secondary" onclick="chatPreset('Como estou para a prova?')">Como estou?</button><button class="btn secondary" onclick="chatPreset('O que revisar hoje?')">O que revisar?</button><button class="btn secondary" onclick="chatPreset('Me dê 5 questões de Ética')">5 de Ética</button></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><h3>Explicação com IA gratuita</h3><textarea id="openq" rows="5" placeholder="Digite a dúvida jurídica. Ex.: Não lembro controle de constitucionalidade."></textarea><button class="btn amber" style="margin-top:8px" onclick="copyGPT()">Copiar prompt para o ChatGPT</button><p id="copymsg" class="muted"></p></div></div>`
}
function chatPreset(t){document.getElementById('chatin').value=t;chatSend()}
function chatSend(){let inp=document.getElementById('chatin'),t=inp.value.trim();if(!t)return;S.chat.push({who:'user',text:t});let l=t.toLowerCase(),r='';
 if(l.includes('40 minuto'))r='Para 40 minutos: 8 min de revisão de erros, 12 min de teoria essencial e 20 min de questões. Priorize '+(statsByDisc().find(x=>x.n>=2&&x.p<70)?.d||'um bloco misto')+'.';
 else if(l.includes('vamos estudar'))r='Certo. '+strip(recommendation())+' Abra a aba Estudar e clique em “Estudo de hoje”.';
 else if(l.includes('como estou'))r=`Você respondeu ${S.answers.length} questões, com ${acc()}% de acerto, e concluiu ${S.sims.length} simulados. ${S.sims.length?'Seu último simulado teve '+S.sims.at(-1).ok+'/'+S.sims.at(-1).total+'.':'Ainda precisamos de um simulado para medir ritmo de prova.'}`;
 else if(l.includes('revisar'))r=dueErrors().length?`Você tem ${dueErrors().length} revisões vencidas. Comece por ${dueErrors().slice(0,3).map(e=>e.disc+' — '+e.topic).join('; ')}.`:'Não há revisão vencida. Faça 10 questões da disciplina com menor desempenho.';
 else if(l.includes('5 questões')&&l.includes('ética')){r='Preparei um bloco de Ética. Abra a aba Estudar; vou iniciar 5 questões agora.';setTimeout(()=>quick('Ética/OAB',5),400)}
 else r='Para essa dúvida aberta, use o campo “Explicação com IA gratuita” ao lado. Ele monta um prompt com seu histórico para você colar no ChatGPT sem API paga.';
 S.chat.push({who:'bot',text:r});save();renderTutor();let c=document.getElementById('chat');if(c)c.scrollTop=c.scrollHeight}
function strip(h){let x=document.createElement('div');x.innerHTML=h;return x.textContent.trim()}
async function copyGPT(){let q=document.getElementById('openq').value.trim();if(!q)return;let weak=statsByDisc().filter(x=>x.n>=2).slice(0,5).map(x=>`${x.d} ${x.p}%`).join(', ');let prompt=`Você é meu tutor de preparação para a 1ª fase do 49º Exame de Ordem, prevista para 09/05/2027. Sou bacharel em Direito e fiquei alguns anos afastada dos estudos. Meu nível inicial informado é: ${S.profile.level}. Já respondi ${S.answers.length} questões neste aplicativo e meu acerto geral é ${acc()}%. Disciplinas com menor desempenho observado: ${weak||'ainda sem dados suficientes'}. Explique de forma atualizada, objetiva e voltada ao padrão da prova. Não invente lei, artigo ou jurisprudência; quando houver risco de desatualização, indique que devo conferir a fonte oficial. Ao final, faça 3 questões autorais curtas para testar se entendi. Minha dúvida é: ${q}`;try{await navigator.clipboard.writeText(prompt);document.getElementById('copymsg').textContent='Prompt copiado. Abra o ChatGPT e cole na conversa.'}catch(e){document.getElementById('openq').value=prompt;document.getElementById('copymsg').textContent='Não foi possível copiar automaticamente. O prompt foi colocado no campo acima para copiar manualmente.'}}