function renderDesempenho(){
 let p=document.getElementById('p-desempenho'),st=statsByDisc();p.innerHTML=`<div class="card"><h1>Desempenho</h1><div class="kpis"><div class="kpi"><span>Acerto geral</span><b>${acc()}%</b></div><div class="kpi"><span>Questões</span><b>${S.answers.length}</b></div><div class="kpi"><span>Erros ativos</span><b>${S.errors.filter(e=>!e.mastered).length}</b></div><div class="kpi"><span>Meta simulado</span><b>50+</b></div></div></div><div class="card" style="margin-top:16px"><h2>Por disciplina</h2><table><thead><tr><th>Disciplina</th><th>Respondidas</th><th>Acerto</th><th>Evolução</th></tr></thead><tbody>${st.map(x=>`<tr class="${x.n>=2?(x.p<60?'weak':x.p>=75?'strong':''):''}"><td>${x.d}</td><td>${x.n}</td><td>${x.n?x.p+'%':'—'}</td><td><div class="progress"><span style="width:${x.p}%"></span></div></td></tr>`).join('')}</tbody></table></div>`}
function renderEdital(){
 let p=document.getElementById('p-edital');p.innerHTML=`<div class="card"><span class="pill warn">AGUARDANDO PUBLICAÇÃO</span><h1>Edital do 49º EOU</h1><p><b>Publicação prevista:</b> 22/01/2027</p><p><b>Inscrições previstas:</b> 29/01/2027 a 05/02/2027</p><p><b>1ª fase prevista:</b> 09/05/2027</p><p><b>2ª fase prevista:</b> 04/07/2027</p><div class="notice">Datas do calendário oficial consultado em setembro de 2026 e sujeitas a alteração. Quando o edital sair, confira disciplinas, regras, horários, documentos e critérios de aprovação.</div><h2>Checklist para janeiro/2027</h2><p>☐ Conferir regras da prova objetiva<br>☐ Conferir disciplinas e distribuição<br>☐ Conferir documentos aceitos<br>☐ Conferir horários e fechamento dos portões<br>☐ Conferir regras da 2ª fase<br>☐ Atualizar o aplicativo se houver mudança</p><p><a href="https://examedeordem.oab.org.br/Calendario" target="_blank" rel="noopener">Abrir calendário oficial da OAB</a></p></div>`}
function renderDados(){
 let p=document.getElementById('p-dados');p.innerHTML=`<div class="grid2"><div class="card"><h1>Privacidade e dados</h1><p>Todo o histórico deste aplicativo fica armazenado <b>neste navegador/dispositivo</b>. Não há conta, servidor, banco de dados remoto ou API paga.</p><div class="notice">Se limpar os dados do navegador ou trocar de aparelho sem backup, o histórico será perdido.</div><button class="btn" onclick="backup()">Exportar backup JSON</button><label style="margin-top:14px">Restaurar backup</label><input type="file" id="restore" accept=".json" onchange="restoreBackup(this.files[0])"></div><div class="card"><h2>Perfil</h2><label>Nome</label><input id="pf-name" value="${esc(S.profile.name)}"><label>Tempo por dia</label><input id="pf-min" type="number" value="${S.profile.minutes}"><label>Dias por semana</label><input id="pf-days" type="number" min="1" max="7" value="${S.profile.days}"><button class="btn secondary" style="margin-top:10px" onclick="saveProfile()">Salvar perfil</button><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><button class="btn bad" onclick="wipe()">Apagar todos os dados deste aparelho</button></div></div>`}
function backup(){let blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup_mentora_oab49_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
function restoreBackup(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.profile||!Array.isArray(x.answers))throw 0;S=x;save();alert('Backup restaurado.');renderDados()}catch(e){alert('Arquivo de backup inválido.')}};r.readAsText(file)}
function saveProfile(){S.profile.name=document.getElementById('pf-name').value.trim();S.profile.minutes=+document.getElementById('pf-min').value||60;S.profile.days=+document.getElementById('pf-days').value||5;save();alert('Perfil salvo.')}
function wipe(){if(confirm('Apagar todo o histórico deste aparelho? Esta ação não pode ser desfeita sem um backup.')){localStorage.removeItem(KEY);location.reload()}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
nav();renderHoje();
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});