const QUESTIONS=window.OAB_QUESTIONS||[];
const EXAM=new Date('2027-05-09T00:00:00-03:00');
const EDITAL=new Date('2027-01-22T00:00:00-03:00');
const KEY='mentoraOAB49_state_v1';
const defaultState={profile:{name:'',minutes:90,days:5,level:'Muito enferrujada',hard:[]},answers:[],errors:[],sessions:[],sims:[],chat:[],started:false};
let S=load();
function load(){try{return Object.assign(structuredClone(defaultState),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function fmtDate(d){return new Intl.DateTimeFormat('pt-BR').format(d)}
function daysTo(d){return Math.max(0,Math.ceil((d-new Date())/86400000))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const discs=[...new Set(QUESTIONS.map(q=>q.disc))];
const pages=[['hoje','Hoje'],['estudar','Estudar'],['questoes','Questões'],['revisoes','Revisões'],['simulados','Simulados'],['tutor','Tutor OAB'],['desempenho','Desempenho'],['edital','Edital 49º'],['dados','Dados']];
function nav(){document.getElementById('nav').innerHTML=pages.map((p,i)=>`<button class="${i===0?'active':''}" onclick="show('${p[0]}',this)">${p[1]}</button>`).join('')}
function show(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('p-'+id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active')); if(b)b.classList.add('active');render(id)}
function acc(){if(!S.answers.length)return 0;return Math.round(100*S.answers.filter(a=>a.ok).length/S.answers.length)}
function dueErrors(){let now=Date.now();return S.errors.filter(e=>!e.mastered && (!e.nextReview || e.nextReview<=now))}
function statsByDisc(){return discs.map(d=>{let a=S.answers.filter(x=>x.disc===d), ok=a.filter(x=>x.ok).length;return{d,n:a.length,p:a.length?Math.round(ok*100/a.length):0}}).sort((a,b)=>(a.p||0)-(b.p||0))}
function render(id){({hoje:renderHoje,estudar:renderEstudar,questoes:renderQuestoes,revisoes:renderRevisoes,simulados:renderSimulados,tutor:renderTutor,desempenho:renderDesempenho,edital:renderEdital,dados:renderDados}[id]||renderHoje)()}
function renderHoje(){
 let p=document.getElementById('p-hoje');
 if(!S.started){p.innerHTML=`<div class="hero"><div class="card"><span class="pill">49º Exame de Ordem</span><h1>Um plano pessoal até 09 de maio de 2027</h1><p>Este aplicativo foi feito para uma bacharel em Direito que ficou alguns anos afastada dos estudos. Ele começa recuperando a base e aumenta o volume de questões conforme o desempenho.</p><div class="notice"><b>Sem mensalidade.</b> Seus dados ficam neste dispositivo. Nenhuma API paga é usada.</div><button class="btn amber" onclick="onboarding()">Começar minha preparação</button></div><div class="card"><div class="muted">Dias para a 1ª fase</div><div class="bigdate">${daysTo(EXAM)}</div><p><b>Data-alvo:</b> 09/05/2027</p><p class="muted">Edital previsto: 22/01/2027. Calendário sujeito a alterações pela OAB.</p></div></div>`;return}
 let weak=statsByDisc().filter(x=>x.n>=2).slice(0,3);
 p.innerHTML=`<div class="hero"><div class="card"><span class="pill good">Plano ativo</span><h1>${S.profile.name?`Olá, ${esc(S.profile.name)}.`:'Preparação em andamento.'}</h1><p>Seu foco agora é construir consistência e elevar gradualmente os simulados para uma margem de segurança de <b>50+ acertos</b>.</p><div class="row"><button class="btn amber" onclick="startToday()">COMEÇAR ESTUDO DE HOJE</button><button class="btn secondary" onclick="show('revisoes')">Revisões pendentes (${dueErrors().length})</button></div></div><div class="card"><div class="muted">Dias para a prova</div><div class="bigdate">${daysTo(EXAM)}</div><div class="progress"><span style="width:${Math.min(100,Math.max(2,(1-daysTo(EXAM)/238)*100))}%"></span></div><p class="muted">${fmtDate(EXAM)} • calendário oficial sujeito a alteração</p></div></div>
 <div class="kpis" style="margin-top:16px"><div class="kpi"><span>Questões</span><b>${S.answers.length}</b></div><div class="kpi"><span>Acerto geral</span><b>${acc()}%</b></div><div class="kpi"><span>Sessões</span><b>${S.sessions.length}</b></div><div class="kpi"><span>Simulados</span><b>${S.sims.length}</b></div></div>
 <div class="grid2" style="margin-top:16px"><div class="card"><h2>Recomendação de hoje</h2>${recommendation()}</div><div class="card"><h2>Pontos que merecem atenção</h2>${weak.length?weak.map(x=>`<p><b>${x.d}</b> — ${x.p}% em ${x.n} questões</p>`).join(''):'<p class="muted">Faça o diagnóstico inicial para o sistema identificar suas fragilidades.</p>'}</div></div>`;
}
function onboarding(){document.getElementById('p-hoje').innerHTML=`<div class="card"><h1>Configuração inicial</h1><div class="grid2"><div><label>Nome</label><input id="ob-name" placeholder="Como deseja ser chamada?"><label>Tempo médio por dia</label><select id="ob-min"><option value="30">30 min</option><option value="60">1 hora</option><option value="90" selected>1h30</option><option value="120">2 horas</option><option value="180">3h+</option></select><label>Dias por semana</label><select id="ob-days"><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option></select></div><div><label>Como você se sente hoje?</label><select id="ob-level"><option>Muito enferrujada</option><option>Intermediária</option><option>Razoavelmente atualizada</option></select><label>Disciplinas mais difíceis (separe por vírgulas)</label><input id="ob-hard" placeholder="Ex.: Processo Civil, Tributário"><div class="notice">Você não precisa estudar tudo de uma vez. O diagnóstico será feito em blocos curtos e pode ser pausado.</div></div></div><button class="btn" onclick="finishOnboarding()">Salvar e iniciar diagnóstico</button></div>`}
function finishOnboarding(){S.profile.name=document.getElementById('ob-name').value.trim();S.profile.minutes=+document.getElementById('ob-min').value;S.profile.days=+document.getElementById('ob-days').value;S.profile.level=document.getElementById('ob-level').value;S.profile.hard=document.getElementById('ob-hard').value.split(',').map(x=>x.trim()).filter(Boolean);S.started=true;save();startDiagnostic()}
let quiz={ids:[],i:0,mode:'study',answers:[],started:0};
function startDiagnostic(){let ids=[];discs.forEach(d=>{let q=QUESTIONS.find(x=>x.disc===d);if(q)ids.push(q.id)}); quiz={ids,i:0,mode:'diagnostic',answers:[],started:Date.now()};show('estudar');renderQuiz()}
function startToday(){let mins=prompt('Quanto tempo você tem hoje?\nDigite minutos: 20, 30, 45, 60, 90 ou 120',S.profile.minutes||60);mins=Math.max(20,Math.min(120,+mins||60));let n=Math.min(20,Math.max(5,Math.round(mins/6)));let weak=statsByDisc().filter(x=>x.n>0&&x.p<65).map(x=>x.d);let pool=QUESTIONS.filter(q=>weak.includes(q.disc)&&!S.answers.some(a=>a.qid===q.id&&a.ok));if(pool.length<n)pool=pool.concat(QUESTIONS.filter(q=>!pool.includes(q)));let ids=shuffle(pool).slice(0,n).map(x=>x.id);quiz={ids,i:0,mode:'study',answers:[],started:Date.now(),mins};show('estudar');renderQuiz()}
function recommendation(){let due=dueErrors().length;if(due)return `<div class="studybox"><b>Prioridade 1: revisar ${due} erro(s) vencido(s).</b><p>Depois, faça um bloco de questões da disciplina com menor desempenho.</p></div>`;let st=statsByDisc().find(x=>x.n>=2&&x.p<70);if(st)return `<div class="studybox"><b>Hoje: ${st.d}</b><p>Seu desempenho nessa disciplina está em ${st.p}%. Faça revisão curta + 8 a 12 questões.</p></div>`;return `<div class="studybox"><b>Faça o diagnóstico ou um bloco misto.</b><p>O sistema ajustará a recomendação assim que houver histórico suficiente.</p></div>`}
function renderEstudar(){let p=document.getElementById('p-estudar');p.innerHTML=`<div class="card"><h1>Estudar</h1><p>Escolha uma sessão rápida ou deixe o sistema montar a sessão do dia.</p><div class="row"><button class="btn amber" onclick="startToday()">Estudo de hoje</button><button class="btn secondary" onclick="startDiagnostic()">Diagnóstico inicial</button><button class="btn secondary" onclick="quick('Ética/OAB',10)">10 de Ética</button><button class="btn secondary" onclick="quick('Constitucional',10)">10 de Constitucional</button></div></div><div id="quizbox"></div>`}
function quick(d,n){let pool=shuffle(QUESTIONS.filter(q=>q.disc===d));if(pool.length<n)pool=shuffle(QUESTIONS);quiz={ids:pool.slice(0,n).map(x=>x.id),i:0,mode:'study',answers:[],started:Date.now()};renderQuiz()}
function renderQuiz(){let box=document.getElementById('quizbox'); if(!box)return;if(quiz.i>=quiz.ids.length){finishQuiz();return}let q=QUESTIONS.find(x=>x.id===quiz.ids[quiz.i]);box.innerHTML=`<div class="card" style="margin-top:16px"><div class="row" style="justify-content:space-between"><span class="pill">${q.disc}</span><span class="muted">${quiz.i+1}/${quiz.ids.length}</span></div><h2 style="margin-top:12px">${esc(q.q)}</h2><div id="opts">${q.opts.map((o,i)=>`<div class="option" onclick="answerQ(${i})"><b>${"ABCD"[i]}.</b> ${esc(o)}</div>`).join('')}</div><div id="feedback"></div></div>`}
function answerQ(i){let q=QUESTIONS.find(x=>x.id===quiz.ids[quiz.i]), ok=i===q.ans;[...document.querySelectorAll('#opts .option')].forEach((el,idx)=>{el.onclick=null;if(idx===q.ans)el.classList.add('correct');if(idx===i&&!ok)el.classList.add('wrong')});let a={qid:q.id,disc:q.disc,topic:q.topic,ok,chosen:i,at:Date.now(),mode:quiz.mode}; S.answers.push(a);quiz.answers.push(a);if(!ok){let e=S.errors.find(x=>x.qid===q.id&&!x.mastered);if(e){e.count++;e.nextReview=Date.now()+86400000}else S.errors.push({qid:q.id,disc:q.disc,topic:q.topic,count:1,type:'não sabia',created:Date.now(),nextReview:Date.now()+86400000,stage:0,mastered:false})}save();document.getElementById('feedback').innerHTML=`<div class="notice"><b>${ok?'Correto.':'Incorreto.'}</b> ${esc(q.exp)}<br><span class="muted">Questão autoral • ${q.diff}</span></div><button class="btn" onclick="nextQ()">Próxima</button>`}
function nextQ(){quiz.i++;renderQuiz()}
function finishQuiz(){let ok=quiz.answers.filter(a=>a.ok).length,total=quiz.answers.length;S.sessions.push({at:Date.now(),mode:quiz.mode,total,ok,minutes:Math.round((Date.now()-quiz.started)/60000)});save();document.getElementById('quizbox').innerHTML=`<div class="card" style="margin-top:16px"><h2>Sessão concluída</h2><div class="bigdate">${ok}/${total}</div><p>Acerto: ${total?Math.round(ok*100/total):0}%.</p><p>${ok/Math.max(total,1)>=.7?'Bom desempenho. Mantenha revisão espaçada.':'Revise os erros antes de avançar. O sistema os colocou no caderno de revisão.'}</p><button class="btn" onclick="show('hoje')">Voltar ao Hoje</button></div>`}