-- Mentora OAB 49 - schema inicial
-- Execute em um projeto Supabase novo.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  exam_date date not null default date '2027-05-09',
  daily_minutes integer not null default 90 check (daily_minutes between 10 and 600),
  study_days integer not null default 5 check (study_days between 1 and 7),
  initial_level text,
  difficult_subjects text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.disciplines (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  discipline_id bigint not null references public.disciplines(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  unique (discipline_id, name)
);

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  legacy_id integer unique,
  discipline_id bigint not null references public.disciplines(id),
  topic_id bigint references public.topics(id),
  prompt text not null,
  options jsonb not null,
  correct_index smallint not null check (correct_index between 0 and 3),
  explanation text not null,
  difficulty text not null default 'Médio',
  source_type text not null default 'autoral',
  source_label text,
  source_url text,
  legal_review_status text not null default 'pendente',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(options) = 'array')
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id uuid references public.questions(id) on delete set null,
  legacy_question_id integer,
  client_event_id uuid not null,
  discipline text not null,
  topic text,
  selected_index smallint,
  is_correct boolean not null,
  confidence smallint check (confidence between 1 and 5),
  error_type text,
  mode text not null default 'study',
  duration_seconds integer,
  answered_at timestamptz not null default now(),
  unique (user_id, client_event_id)
);

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  client_event_id uuid not null,
  mode text not null,
  planned_minutes integer,
  actual_minutes integer,
  total_questions integer not null default 0,
  correct_questions integer not null default 0,
  started_at timestamptz,
  ended_at timestamptz not null default now(),
  unique (user_id, client_event_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id uuid references public.questions(id) on delete cascade,
  legacy_question_id integer,
  stage smallint not null default 0,
  repetitions integer not null default 0,
  due_at timestamptz not null default now(),
  mastered boolean not null default false,
  last_result boolean,
  updated_at timestamptz not null default now()
);

create unique index if not exists reviews_user_question_uq
on public.reviews(user_id, coalesce(question_id::text, 'legacy:' || coalesce(legacy_question_id::text,'')));

create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  client_event_id uuid not null,
  size integer not null,
  correct_count integer not null,
  duration_seconds integer,
  completed_at timestamptz not null default now(),
  unique(user_id, client_event_id)
);

create table if not exists public.simulation_items (
  id bigint generated by default as identity primary key,
  simulation_id uuid not null references public.simulations(id) on delete cascade,
  question_id uuid references public.questions(id) on delete set null,
  legacy_question_id integer,
  selected_index smallint,
  is_correct boolean not null
);

create table if not exists public.ai_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  mode text not null default 'explain',
  discipline text,
  response_text text,
  sources jsonb not null default '[]'::jsonb,
  model text,
  created_at timestamptz not null default now()
);

create table if not exists public.legal_search_cache (
  id uuid primary key default gen_random_uuid(),
  query_hash text not null unique,
  query text not null,
  source text not null,
  payload jsonb not null,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists attempts_user_time_idx on public.attempts(user_id, answered_at desc);
create index if not exists attempts_user_disc_idx on public.attempts(user_id, discipline);
create index if not exists sessions_user_time_idx on public.study_sessions(user_id, ended_at desc);
create index if not exists simulations_user_time_idx on public.simulations(user_id, completed_at desc);
create index if not exists reviews_due_idx on public.reviews(user_id, mastered, due_at);

-- RLS
alter table public.profiles enable row level security;
alter table public.attempts enable row level security;
alter table public.study_sessions enable row level security;
alter table public.reviews enable row level security;
alter table public.simulations enable row level security;
alter table public.simulation_items enable row level security;
alter table public.ai_interactions enable row level security;
alter table public.disciplines enable row level security;
alter table public.topics enable row level security;
alter table public.questions enable row level security;
alter table public.legal_search_cache enable row level security;

create policy "profile own select" on public.profiles for select using (auth.uid() = id);
create policy "profile own insert" on public.profiles for insert with check (auth.uid() = id);
create policy "profile own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "disciplines authenticated read" on public.disciplines for select to authenticated using (active = true);
create policy "topics authenticated read" on public.topics for select to authenticated using (active = true);
create policy "questions authenticated read" on public.questions for select to authenticated using (active = true);

create policy "attempt own select" on public.attempts for select using (auth.uid() = user_id);
create policy "attempt own insert" on public.attempts for insert with check (auth.uid() = user_id);
create policy "session own select" on public.study_sessions for select using (auth.uid() = user_id);
create policy "session own insert" on public.study_sessions for insert with check (auth.uid() = user_id);
create policy "reviews own all" on public.reviews for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "sim own select" on public.simulations for select using (auth.uid() = user_id);
create policy "sim own insert" on public.simulations for insert with check (auth.uid() = user_id);
create policy "simitem own select" on public.simulation_items for select using (
  exists(select 1 from public.simulations s where s.id = simulation_id and s.user_id = auth.uid())
);
create policy "simitem own insert" on public.simulation_items for insert with check (
  exists(select 1 from public.simulations s where s.id = simulation_id and s.user_id = auth.uid())
);
create policy "ai own select" on public.ai_interactions for select using (auth.uid() = user_id);
create policy "ai own insert" on public.ai_interactions for insert with check (auth.uid() = user_id);

-- legal_search_cache deve ser acessado apenas por Edge Functions usando service role.

-- Cria perfil automaticamente no cadastro.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, display_name)
  values(new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
